# 服务端口
server:
  port: 8305

spring:
  application:
    name: service-wechat
  # 环境设置：dev、test、prod
  profiles:
    active:
      dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  #返回json的全局时间格式
  jackson:
    date-format=yyyy-MM-dd HH:mm:ss
    time-zone=GMT+8
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/ggkt/user/mapper/xml/*.xml

# 公众号id和秘钥
# 硅谷课堂微信公众平台appId
wechat:
  mp-app-id: wx09f201e9013e81d8
  # 硅谷课堂微信公众平台api秘钥
  mp-app-secret: 6c999765c12c51850d28055e8b6e2eda