# 服务端口
server:
  port: 8305

spring:
  application:
    name: service-wechat
  # 环境设置：dev、test、prod
  profiles:
    active:
      dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_wechat?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  #返回json的全局时间格式
  jackson:
    date-format=yyyy-MM-dd HH:mm:ss
    time-zone=GMT+8
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    # mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/ggkt/wechat/mapper/xml/*.xml

wx:
  wx-mp-template-message-object: {
    "2WOzacjuyXuTWESj17xl9TwHBg0gAYlK5aG9TJj0GkM", "http://ggkt2.vipgz1.91tunnel.com/#/pay/"
  }
  mp:
    # 公众号的 appid
    app-id: wxc2d7509ddd5c9418
    # 公众号的 appsecret
    secret: 92197f5f41d968266f1ba20b12293574
    # 公众号的 token
    token: ggkt
