# 服务端口
server:
  port: 8333

spring:
  # 服务名
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由配置
      routes: [
        { id: service-vod, uri: lb://service-vod, predicates: Path=/admin/vod/** },
        { id: service-order, uri: lb://service-order, predicates: Path=/admin/order/** },
        { id: service-activity, uri: lb://service-activity, predicates: Path=/admin/activity/** },
        { id: service-user, uri: lb://service-user, predicates: Path=/admin/user/** },
        { id: service-wechat, uri: lb://service-wechat, predicates: Path=/admin/wechat/** },
      ]
